examples = [
    ('AC/DC - Back In Black', 'pAgnJDJN4VA'),
    ('Eminem - Not Afraid', 'j5-yKhDd64s'),
    ('Katy Perry - Hot N Cold', 'kTHNpusq654'),
    ('Katy Perry - Rise', 'hdw1uKiTI5c'),
    ('Madonna - Hung Up', 'EDwb9jOVRtU'),
    ('Oxxxymiron - Город под подошвой', 'XBleNfmkScA'),
    ('Oxxxymiron - Где нас нет', 'CFKhLYqUA0Q'),
    ('Lady Gaga - Perfect Illusion', 'oB94lvJbETE'),
    ('Lady Gaga - Applause', '_bHhpufKRjs'),
    ('Taylor Swift - Blank Space', 'e-ORhEE9VVg'),
    ('OneRepublic - Counting Stars', 'hT_nvWreIhg'),
    ('Pharrell Williams - Happy', 'y6Sxv-sUYtM'),
    ('Dr. Dre - Still D.R.E.', '_CL6n0FJZpk'),
    ('Linkin Park - Numb', 'kXYiU_JCYtU'),
    ('Metallica - Hardwired', 'uhBHL3v4d3I'),
    ('Eminem - Lose Yourself', 'xFYQQPAOz7Y'),
    ('Iron Maiden - Aces High', 'Xg9aQvjMS60'),
    ('50 Cent - In Da Club', '5qm8PH4xAss'),
    ('Macklemore & Ryan Lewis - Can\'t Hold Us', '2zNSgSzhBfM'),
    ('Shawn Mendes - Stitches', 'VbfpW0pbvaU'),
    ('Iron House - Enter Sandman', '3c7bISLhVl8'),
]

hardcoded = {
    'pAgnJDJN4VA': 'rock',
    'kTHNpusq654': 'pop',
    'WbxH5S9_A3M': 'rock',
    'EDwb9jOVRtU': 'pop',
    'j5-yKhDd64s': 'hip-hop',
    '_bHhpufKRjs': 'pop',
    'bESGLojNYSo': 'pop',
    'kXYiU_JCYtU': 'rock',
    'uhBHL3v4d3I': 'rock',
    '_dK2tDK9grQ': 'pop',
    'XurWUn5_S_E': 'jazz',
}
